delta = 30

[double]
origin = "."
mode = "double"
keyring = "keyring.json"
unsigned = "root.unsigned"
signed = "root.signed_double"
reload = "echo reloading"

[single]
origin = "."
mode = "single"
keyring = "keyring.json"
unsigned = "root.unsigned"
signed = "root.signed_single"
reload = "echo reloading"
