delta = 10

[default]
origin = "."
mode = "double"
keyring = "keyring.json"
upstream = "root.zone"
unsigned = "root.unsigned"
signed = "root.signed"
anchors = "root.anchors"
hints = "root.hints"
dashboard = "dashboard.html"
dnskey_ttl = 60
#reload = "echo reloading"

[double]
origin = "."
mode = "double"
keyring = "keyring.json"
unsigned = "root.unsigned"
signed = "root.signed_double"
reload = "echo reloading"

[single]
origin = "."
mode = "single"
keyring = "keyring.json"
unsigned = "root.unsigned"
signed = "root.signed_single"
reload = "echo reloading"
