delta = 30

[default]
mode = "double"
#mode = "single"

origin = "."
keyring = "/storage/keyring.json"
upstream = "/storage/root.upstream"
unsigned = "/storage/root.unsigned"
signed = "/storage/root.zone"
hints =  "/var/www/html/root.hints"
anchors =  "/var/www/html/root.anchors"
dashboard = "/var/www/html/index.html"
reload = "nsd-control reload"
